baseURL = "https://rafed.github.io/blog/"
#CanonifyURLs=true
pluralizeListTitles = false
summaryLength   = 35

theme           = "BlogRa"
languageCode    = "en-us"
title           = "RaBlog"

disqusShortname = "rafed"
googleAnalytics = "UA-106132552-1"

[params]
    description  = "My thoughts in my blogs"
    contactEmail = "rafed123@gmail.com"
    footer       = "© 2021 Rafed Muhammad Yasir."
    googleSearch = "000151824860492892407:kd5zijxwj6a"
    adsense      = "ca-pub-7125931910131040"
    math         = false   # best to enable this in the front matter of a page
    mermaid      = false   # best to enable this in the front matter of a page

    # Social Media Params
    facebook   = "https://www.facebook.com/devrafed"
    twitter    = ""
    youtube    = "https://www.youtube.com/channel/UCm06Y0e-rYROhZ76-GLtYTQ"
    instagram  = ""
    github     = ""
    pinterest  = ""
    linkedin   = "https://www.linkedin.com/in/rafed-m-yasir/"


# Configure the site menu here
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        weight = 2
            [[menu.main]]
                parent = "blog"
                name = "Posts"
                url = "/posts/"
                weight = 1
            [[menu.main]]
                parent = "blog"
                name = "Sections"
                url = "/sections/"
                weight = 2
            [[menu.main]]
                parent = "blog"
                name = "divider"
                weight = 3
            [[menu.main]]
                parent = "blog"
                name = "Tags"
                url = "/tags/"
                weight = 4
    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 3
    [[menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 4


# Don't touch this
[markup.goldmark.renderer]
    unsafe = true